Chaos config read both from file and string
picodata/xk6-khorne pull request #3
Opened 2024-11-03 12:47 UTC by dodokek

Add functionality to read chaos config from file and YAML string

2024-11-05 13:04 UTC, lowitea requested changes

2024-11-05 13:04 UTC, lowitea commented on examples/kill_master_node.js
> -    "./examples/chaosmesh/kill_master_node.yaml"
It seems you forgot to delete this file.

2024-11-05 13:04 UTC, lowitea commented on examples/kill_master_node.js
> +    apiVersion: "chaos-mesh.org/v1alpha1",
These two fields seem to always be the same, maybe add them automatically inside the RunChaosExperiment function?

2024-11-05 13:04 UTC, lowitea commented on examples/kill_master_node.js
> +      namespace: "test-namespace",
You require passing the namespace twice. Maybe you can create all the metadata yourself? Or use the namespace from metadata?

2024-11-05 13:04 UTC, lowitea commented on khorne.go
> +	"github.com/dop251/goja"
You forgot to run tidy command.

2024-11-05 13:04 UTC, lowitea commented on khorne.go
> +func (p *Chaos) RunChaosExperiment(call goja.FunctionCall, runtime *goja.Runtime) goja.Value {
Why did you change the arguments to goja?

2024-11-05 13:04 UTC, lowitea commented on khorne.go
> +	return runtime.ToValue(response)
This code is structured strangely. Here it would be better to form an error response structure in case of error and a successful structure in case of success.

```suggestion
	if err := chaos.RunChaosExperiment(namespace, manifestStruct); err != nil {
		return runtime.ToValue(map[string]interface{}{"success": false, "error": err.Error()})
	}

	return runtime.ToValue(map[string]interface{}{"success": true, "error": ""})
```

2024-11-05 13:04 UTC, lowitea commented on khorne.go
>  }
nit: This order of the fields is more efficient:

```go
type Result struct {
	Error   string `json:"error,omitempty"`
	Success bool   `json:"success"`
}
```

2024-11-05 13:04 UTC, lowitea commented on src/chaos/controller.go
> +func RunChaosExperiment(namespace string, manifestObj *unstructured.Unstructured) error {
You don't need Obj postfix. Golang is a typed language, it's clear here that it's not a string.

2024-11-05 13:04 UTC, lowitea commented on src/chaos/controller.go
> +	}
You don't need these lines in two functions. You can run RunChaosExperiment function from RunChaosExperimentFile.

2024-11-05 14:29 UTC, dodokek commented on khorne.go
> +func (p *Chaos) RunChaosExperiment(call goja.FunctionCall, runtime *goja.Runtime) goja.Value {
In order to handle the object, passed in JS code. Maybe there is another way of parsing the object with chaos manifest, I've chosen method, that I knew already.

2024-11-18 13:16 UTC, lowitea approved these changes

2024-11-18 13:16 UTC, merged